services:
  todo-api:
    build:
      context: todo-api
      target: development
    volumes:
      - ./todo-api:/app
      - /app/node_modules   # prevent host mount from clobbering container's node_modules
    ports:
      - "3000:3000"
