export var PERSISTENCE_METHOD;
(function (PERSISTENCE_METHOD) {
    PERSISTENCE_METHOD["INMEMORY"] = "in_memory";
    PERSISTENCE_METHOD["SQLITE"] = "sqlite";
})(PERSISTENCE_METHOD || (PERSISTENCE_METHOD = {}));
